VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |
    config.ssh.insert_key = false
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
    end

    #Application server 1.
    config.vm.define "app1" do |app|
        app.vm.hostname = "orc-app1.dev"
        app.vm.box = "GospodinovM/ubuntu-20.04-minimal"
        app.vm.box_version = "0.0.2"
        app.vm.network :private_network, ip: "192.168.10.4"
    end

    #Application server 2.
    config.vm.define "app2" do |app|
        app.vm.hostname = "orc-app2.dev"
        
        app.vm.box = "minimal/centos7"
        app.vm.box_version = "7.0"
        app.vm.network :private_network, ip: "192.168.10.2"
    end
end
